#apiVersion: "v1"
#kind: "Namespace"
#metadata:
#  name: "shopping"
#---
apiVersion: akka.lightbend.com/v1
kind: AkkaMicroservice
metadata:
  name: machine-data-service
  namespace: "shopping"
spec:
  replicas: 1
  imagePullSecrets:
    - "unomic"
  image: unomic.registry.jetbrains.space/p/elfin-ap/containers/sirjin-data-service:0.0.0-3-d90b656c-20220414-1551
  javaOptions: "-Xlog:gc -XX:InitialRAMPercentage=75 -XX:MaxRAMPercentage=75"
  resources:
    limits:
      memory: "2Gi"
    requests:
      memory: "2Gi"
      cpu: "1"
