#apiVersion: "v1"
#kind: "Namespace"
#metadata:
#  name: "shopping"
#---
apiVersion: akka.lightbend.com/v1
kind: AkkaMicroservice
metadata:
  name: sirjin-summary-service
  namespace: "sirjin"
spec:
  replicas: 1
  imagePullSecrets:
    - "unomic"
  image: unomic.registry.jetbrains.space/p/sirjin/containers/sirjin-summary-service:latest
  envSecret:
    secretName: "default"
  javaOptions: "-Xlog:gc -XX:InitialRAMPercentage=75 -XX:MaxRAMPercentage=75"
  resources:
    limits:
      memory: "2Gi"
    requests:
      memory: "2Gi"
      cpu: "0.5"
